title: Personal Blog
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://khaitranquang.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Tran Quang Khai # add your name
author-img: kazz.jpg # add your photo
about-author: Hi! Welcome to my personal blog. I am a student at Hanoi University of Science and Technology. Junior Javascript back-end developer. Always hungry to keep learning. # add description
twitter: # add your Twitter handle
facebook: tran.quangkhai97 # add your Facebook handle
github: khaitranquang # add your Github handle
linkedin: # add your Linkedin handle
email: khai.tranquang.8797@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
